"""
README
------
Plot monitor history files generated by CHAPSim2.

Default input files written by ``src/io_monitor.f90``:
- ``domain1_monitor_metrics_history.log``
  columns:
    1 time
    2 global mass balance
    3 max. mass conservation (interior)
    4 max. mass conservation (inlet)
    5 max. mass conservation (outlet)
    6 total kinetic energy
    7 mean dpdx
    8 global pressure drop
    9 bulk velocity qx
   10 bulk velocity qy
   11 bulk velocity qz
   12-16 optional thermo quantities
- ``domain1_monitor_change_history.log``
  columns:
    1 time
    2 max. mass conservation (interior)
    3 max. mass conservation (inlet)
    4 max. mass conservation (outlet)
    5 total mass change rate
    6 kinetic energy change rate

Comment lines starting with ``#`` are ignored automatically.

Examples:
    python3 plot_monitor_bulk_change_history.py
    python3 plot_monitor_bulk_change_history.py --stride 20 --output my_plot.png

Author: W Wang (STFC)
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


DEFAULT_STRIDE = 10
DEFAULT_METRICS_FILE = "domain1_monitor_metrics_history.log"
DEFAULT_CHANGE_FILE = "domain1_monitor_change_history.log"
DEFAULT_OUTPUT_FILE = "monitor_history.png"

IDX_TIME = 0
IDX_GLOBAL_MASS_BALANCE = 1
IDX_MASS_INTERIOR = 2
IDX_MASS_INLET = 3
IDX_MASS_OUTLET = 4
IDX_TOTAL_KINETIC_ENERGY = 5
IDX_MEAN_DPDX = 6
IDX_PRESSURE_DROP = 7
IDX_QX = 8
IDX_QY = 9
IDX_QZ = 10

IDX_CHANGE_TIME = 0
IDX_CHANGE_MASS_INTERIOR = 1
IDX_CHANGE_MASS_INLET = 2
IDX_CHANGE_MASS_OUTLET = 3
IDX_CHANGE_DMDT = 4
IDX_CHANGE_DKEDT = 5

MIN_METRICS_COLUMNS = 11
MIN_CHANGE_COLUMNS = 6


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot CHAPSim2 monitor metrics and change-history logs."
    )
    parser.add_argument(
        "--stride",
        type=int,
        default=DEFAULT_STRIDE,
        help="Plot every Nth sample to reduce point density (default: 10).",
    )
    parser.add_argument(
        "--metrics-file",
        "--bulk-file",
        dest="metrics_file",
        default=DEFAULT_METRICS_FILE,
        help=(
            "Metrics-history log file "
            f"(default: {DEFAULT_METRICS_FILE})."
        ),
    )
    parser.add_argument(
        "--change-file",
        default=DEFAULT_CHANGE_FILE,
        help=(
            "Change-history log file "
            f"(default: {DEFAULT_CHANGE_FILE})."
        ),
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT_FILE,
        help=f"Output figure name (default: {DEFAULT_OUTPUT_FILE}).",
    )
    return parser.parse_args()


def resolve_input_path(filename: str) -> Path:
    path = Path(filename)
    if path.exists():
        return path

    local_path = Path(__file__).resolve().parent / filename
    if local_path.exists():
        return local_path

    raise FileNotFoundError(f"Required file not found: {filename}")


def read_monitor_file(filename: str, min_columns: int) -> np.ndarray:
    path = resolve_input_path(filename)
    data = np.loadtxt(path, comments="#")
    data = np.atleast_2d(data)

    if data.shape[1] < min_columns:
        raise ValueError(
            f"{path} has {data.shape[1]} columns, expected at least {min_columns}."
        )

    return data


def apply_plot_style() -> None:
    plt.style.use("default")
    plt.rcParams["figure.facecolor"] = "white"
    plt.rcParams["axes.facecolor"] = "white"
    plt.rcParams["savefig.facecolor"] = "white"
    plt.rcParams["axes.edgecolor"] = "black"
    plt.rcParams["axes.labelcolor"] = "black"
    plt.rcParams["xtick.color"] = "black"
    plt.rcParams["ytick.color"] = "black"
    plt.rcParams["legend.frameon"] = True
    plt.rcParams["legend.facecolor"] = "white"
    plt.rcParams["legend.edgecolor"] = "black"


def decimate(data: np.ndarray, stride: int) -> np.ndarray:
    return data[::stride]


def plot_monitor_history(
    metrics_data: np.ndarray, change_data: np.ndarray, stride: int, output: str
) -> Path:
    metrics = decimate(metrics_data, stride)
    changes = decimate(change_data, stride)

    fig, axes = plt.subplots(4, 2, figsize=(14, 14), sharex=False)
    axes = axes.ravel()

    axes[0].plot(
        metrics[:, IDX_TIME],
        metrics[:, IDX_TOTAL_KINETIC_ENERGY],
        color="tab:blue",
        linewidth=1.4,
    )
    axes[0].set_xlabel("Time")
    axes[0].set_ylabel("Total kinetic energy")

    axes[1].plot(
        metrics[:, IDX_TIME],
        metrics[:, IDX_QX],
        color="tab:red",
        linewidth=1.4,
    )
    axes[1].set_xlabel("Time")
    axes[1].set_ylabel("Bulk velocity qx")

    axes[2].plot(
        metrics[:, IDX_TIME],
        metrics[:, IDX_QY],
        color="tab:green",
        linewidth=1.4,
    )
    axes[2].set_xlabel("Time")
    axes[2].set_ylabel("Bulk velocity qy")

    axes[3].plot(
        metrics[:, IDX_TIME],
        metrics[:, IDX_QZ],
        color="tab:orange",
        linewidth=1.4,
    )
    axes[3].set_xlabel("Time")
    axes[3].set_ylabel("Bulk velocity qz")

    axes[4].plot(
        changes[:, IDX_CHANGE_TIME],
        changes[:, IDX_CHANGE_MASS_INTERIOR],
        color="tab:blue",
        linewidth=1.2,
        label="interior",
    )
    axes[4].plot(
        changes[:, IDX_CHANGE_TIME],
        changes[:, IDX_CHANGE_MASS_INLET],
        color="tab:red",
        linewidth=1.2,
        label="inlet",
    )
    axes[4].plot(
        changes[:, IDX_CHANGE_TIME],
        changes[:, IDX_CHANGE_MASS_OUTLET],
        color="tab:green",
        linewidth=1.2,
        label="outlet",
    )
    axes[4].set_xlabel("Time")
    axes[4].set_ylabel("Max mass conservation")
    axes[4].legend()

    axes[5].plot(
        metrics[:, IDX_TIME],
        metrics[:, IDX_GLOBAL_MASS_BALANCE],
        color="tab:purple",
        linewidth=1.4,
        label="global mass balance",
    )
    axes[5].plot(
        changes[:, IDX_CHANGE_TIME],
        changes[:, IDX_CHANGE_DMDT],
        color="tab:brown",
        linewidth=1.2,
        label="dM/dt",
    )
    axes[5].set_xlabel("Time")
    axes[5].set_ylabel("Mass balance / change")
    axes[5].legend()

    axes[6].plot(
        changes[:, IDX_CHANGE_TIME],
        changes[:, IDX_CHANGE_DKEDT],
        color="tab:orange",
        linewidth=1.4,
    )
    axes[6].set_xlabel("Time")
    axes[6].set_ylabel("d(KE)/dt")

    axes[7].plot(
        metrics[:, IDX_TIME],
        metrics[:, IDX_MEAN_DPDX],
        color="tab:brown",
        linewidth=1.4,
        label="mean dpdx",
    )
    axes[7].plot(
        metrics[:, IDX_TIME],
        metrics[:, IDX_PRESSURE_DROP],
        color="tab:cyan",
        linewidth=1.4,
        label="pressure drop",
    )
    axes[7].set_xlabel("Time")
    axes[7].set_ylabel("Pressure metrics")
    axes[7].legend()

    for ax in axes:
        ax.grid(True, color="0.85", linewidth=0.8)

    fig.suptitle("CHAPSim2 Monitor History", fontsize=16)
    fig.tight_layout()

    output_path = Path(output)
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(fig)
    return output_path.resolve()


def main() -> None:
    args = parse_args()

    if args.stride <= 0:
        raise ValueError("--stride must be a positive integer.")

    apply_plot_style()

    metrics_data = read_monitor_file(args.metrics_file, MIN_METRICS_COLUMNS)
    change_data = read_monitor_file(args.change_file, MIN_CHANGE_COLUMNS)
    output_path = plot_monitor_history(
        metrics_data, change_data, args.stride, args.output
    )

    print(f"Saved plot to {output_path}")


if __name__ == "__main__":
    main()
