"""
README:
-------
This script is designed to plot monitor point data generated by CHAPSim2.
It creates separate figures for each monitor point, with all variables 
(u, v, w, p, phi) plotted as subplots within each figure.

Features:
- Creates one figure per monitor point
- Each figure contains subplots for all variables (u, v, w, p, phi) 
- Handles both isothermal and thermal flow cases
- Skips every M points for clearer visualization
- Saves high-resolution PNG output for each monitor point
- Optional temperature data for thermal cases

Data format:
- The data and this script should be stored in the folder ./3_monitor/
- Files should be named: domain1_monitor_ptX_flow.dat (where X is the point number)
- Each file contains columns: time, u, v, w, p, phi, [T]
- First 3 lines are skipped (header)

Usage:
1. Ensure the following data structure:
   - ../3_monitor/: Contains both monitor point data files and this script.
2. Run: python3 plot_individual_monitor_points.py

Author: Modified from original by W Wang (STFC)
"""

import numpy as np
import matplotlib.pyplot as plt
import glob
import os

def read_monitor_data(filename):
    """Read data from monitor point file."""
    if not os.path.exists(filename):
        print(f"File {filename} not found")
        return None
        
    try:
        data = np.genfromtxt(filename, skip_header=3, usecols=range(6))
        if data is None or len(data) == 0:
            print(f"No data read from {filename}")
            return None
        return data
    except Exception as e:
        print(f"Error reading {filename}: {str(e)}")
        return None

def plot_single_monitor_point(point_num, M):
    """Plot all variables for a single monitor point in one figure."""
    filename = f'domain1_monitor_pt{point_num}_flow.dat'
    data = read_monitor_data(filename)
    
    if data is None:
        print(f"Cannot plot monitor point {point_num} - no valid data")
        return False
        
    print(f"Plotting monitor point {point_num}...")
    
    # Create figure with subplots for this monitor point
    variables = ['u', 'v', 'w', 'p', 'phi']
    fig, axes = plt.subplots(len(variables), 1, figsize=(12, 15), sharex=True)
    fig.suptitle(f'Monitor Point {point_num} - All Variables', fontsize=16, fontweight='bold')
    
    # Skip every M points for clearer visualization
    time = data[::M, 0]
    
    # Plot each variable in its own subplot
    for j, var in enumerate(variables):
        variable_data = data[::M, j+1]
        
        axes[j].plot(time, variable_data, 
                    linestyle='-', 
                    linewidth=1.5,
                    color=f'C{j}',  # Use different colors for each variable
                    alpha=0.8)
        
        axes[j].set_ylabel(f'{var}', fontsize=12, fontweight='bold')
        axes[j].grid(True, alpha=0.3)
        axes[j].tick_params(axis='both', which='major', labelsize=10)
        
        # Add some statistics to each subplot
        mean_val = np.mean(variable_data)
        std_val = np.std(variable_data)
        axes[j].text(0.02, 0.98, f'Mean: {mean_val:.4f}\nStd: {std_val:.4f}', 
                    transform=axes[j].transAxes, 
                    verticalalignment='top',
                    bbox=dict(boxstyle='round', facecolor='white', alpha=0.8),
                    fontsize=9)
    
    # Set xlabel for bottom subplot
    axes[-1].set_xlabel('Time', fontsize=12, fontweight='bold')
    
    plt.tight_layout()
    
    # Save figure with point-specific name
    output_filename = f'monitor_point_{point_num}_plot.png'
    plt.savefig(output_filename, dpi=300, bbox_inches='tight')
    print(f"  - Saved as '{output_filename}'")
    plt.close()
    
    return True

def plot_individual_monitor_points(N, M, R):
    """Plot each monitor point in its own separate figure."""
    print(f"\nStarting to plot {N} individual monitor points...")
    print(f"Skipping {R} rows.\n")
    print(f"Sampling interval: every {M} points\n")
    
    successful_plots = 0
    created_files = []
    
    for i in range(1, N+1):
        success = plot_single_monitor_point(i, M)
        if success:
            successful_plots += 1
            created_files.append(f'monitor_point_{i}_plot.png')
    
    # Summary
    print(f"\n" + "="*60)
    print(f"PLOTTING COMPLETE")
    print(f"="*60)
    print(f"Successfully plotted: {successful_plots}/{N} monitor points")
    
    if created_files:
        print(f"\nCreated files:")
        for file in created_files:
            print(f"  - {file}")
    else:
        print("\nNo plots were created. Please check your data files.")
    
    return successful_plots

def list_available_files():
    """List available monitor point files in current directory."""
    pattern = 'domain1_monitor_pt*_flow.dat'
    files = glob.glob(pattern)
    
    if files:
        print(f"Found {len(files)} monitor point files:")
        for file in sorted(files):
            print(f"  - {file}")
        
        # Extract point numbers
        point_numbers = []
        for file in files:
            try:
                # Extract number from filename like domain1_monitor_pt1_flow.dat
                parts = file.split('_pt')[1].split('_')[0]
                point_numbers.append(int(parts))
            except:
                continue
        
        if point_numbers:
            max_point = max(point_numbers)
            min_point = min(point_numbers)
            print(f"\nPoint number range: {min_point} to {max_point}")
            return max_point
    else:
        print("No monitor point files found matching pattern: domain1_monitor_pt*_flow.dat")
        return 0

if __name__ == "__main__":
    print("Individual Monitor Point Plotter")
    print("="*40)
    print("Creates separate figures for each monitor point")
    print("Each figure contains all variables (u, v, w, p, phi) as subplots\n")
    
    # List available files
    max_available = list_available_files()
    
    if max_available == 0:
        print("\nNo monitor point files found. Please check your file names and location.")
        exit(1)
    
    print(f"\n" + "-"*40)
    
    # Get user input for number of points
    while True:
        try:
            N = int(input(f"Enter the number of monitor points to plot (1-{max_available}): "))
            if 1 <= N <= max_available:
                break
            else:
                print(f"Please enter a number between 1 and {max_available}")
        except ValueError:
            print("Please enter a valid integer")
            
    # Get user input for skipping rows
    while True:
        try:
            R = int(input("Enter number of lines to skip at the top of the files:"))
            if R > 0:
                break
            else:
                print("Please enter a positive integer")
        except ValueError:
            print("Please enter a valid integer")
    
    # Get user input for sampling interval
    while True:
        try:
            M = int(input("Enter sampling interval (skip every M points for clearer visualization): "))
            if M > 0:
                break
            else:
                print("Please enter a positive integer")
        except ValueError:
            print("Please enter a valid integer")
    
    # Create the plots
    successful = plot_individual_monitor_points(N, M, R)
    
    if successful == 0:
        print("\nNo plots were created. Please check your input files.")
    else:
        print(f"\nPlotting completed successfully!")
        print(f"Each monitor point has been saved as a separate PNG file.")
