"""
README:
-------
This script is designed to plot monitor point data generated by CHAPSim2.
It reads and visualizes time series data for multiple variables (u, v, w, p, phi)
from monitor points, with optional temperature data for thermal cases.

Features:
- Plots multiple monitor points with different markers and colors
- Handles both isothermal and thermal flow cases
- Skips every M points for clearer visualization
- Saves high-resolution PNG output

Data format:
- The data and this script should be stored in the folder ./3_monitor/
- Files should be named: domain1_monitor_ptX_flow.dat (where X is the point number)
- Each file contains columns: time, u, v, w, p, phi, [T]
- First 3 lines are skipped (header)

Usage:
1. Ensure the following data structure:
   - ../3_monitor/: Contains both monitor point data files and this script.
2. Run: python3 plot_monitor_points.py

Author: W Wang (STFC)
"""

import numpy as np
import matplotlib.pyplot as plt
import glob
import os

def read_monitor_data(filename):
    """Read data from monitor point file."""
    if not os.path.exists(filename):
        print(f"File {filename} not found")
        return None
        
    try:
        data = np.genfromtxt(filename, skip_header=3, usecols=range(6))
        if data is None or len(data) == 0:
            print(f"No data read from {filename}")
            return None
        return data
    except Exception as e:
        print(f"Error reading {filename}: {str(e)}")
        return None

def plot_monitor_points(N, M):
    """Plot monitor points data for N points."""
    print("\nStarting to plot monitor points...")
    
    # Create figure with subplots
    variables = ['u', 'v', 'w', 'p', 'phi']
    fig, axes = plt.subplots(len(variables), 1, figsize=(12, 15), sharex=True)
    fig.suptitle('Monitor Points Data')
    
    # Colors for different monitor points
    colors = plt.cm.rainbow(np.linspace(0, 1, N))
    
    # Different marker styles for variety
    markers = ['o', 's', '^', 'v', 'D', 'p', 'h', '8']
    
    data_found = False  # Flag to check if any data was successfully plotted
    successful_files = []  # List to store successfully plotted files
    
    for i in range(1, N+1):
        filename = f'domain1_monitor_pt{i}_flow.dat'
        data = read_monitor_data(filename)
        if data is None:
            continue
            
        data_found = True
        successful_files.append(filename)
        print(f"Successfully reading data from: {filename}")
        
        # Skip every 100 points
        time = data[::M, 0]
        
        # Plot each variable
        for j, var in enumerate(variables):
            axes[j].plot(time, data[::M, j+1], 
                        marker=markers[i % len(markers)],  # Cycle through markers
                        linestyle='none',  # No lines between points
                        label=f'Point {i}', 
                        color=colors[i-1],
                        markersize=4)  # Smaller markers for clarity
            axes[j].set_ylabel(f'{var}')
            axes[j].grid(True)
            axes[j].legend()
    
    if not data_found:
        print("\nNo valid data found for any monitor point")
        plt.close()
        return
        
    # Set xlabel for bottom subplot
    axes[-1].set_xlabel('Time')
    
    plt.tight_layout()
    plt.savefig('monitor_points_plot.png', dpi=300, bbox_inches='tight')
    print("\nPlot saved as 'monitor_points_plot.png'")
    print(f"\nSuccessfully plotted {len(successful_files)} files:")
    for file in successful_files:
        print(f"- {file}")
    plt.close()

if __name__ == "__main__":
    N = int(input("Enter the number of monitor points to plot: "))
    M = int(input("Enter sampling interval (skip every M points for clearer visualization): "))
    plot_monitor_points(N, M)
